---
MAIN:
  hosts:
    SWT001:
      ansible_host: 1.1.1.1
      config_file: /home/user/ansible/ansible_playbooks/remove_from_prov_net/generated_configs/1.1.1.1_remove_from_prov.ios
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubanetworks.aoscx.aoscx
...
