---
aruba_switches:
  children: # defining child groups
    SITE_1:
      hosts:
        prov_switch:
          ansible_host: 1.2.3.4
    S0123:
      hosts:
        S0123SWT001:
          ansible_host: 4.5.6.7
  vars:
    ansible_connection: network_cli # <-- CLI connection method
    ansible_network_os: arubanetworks.aoscx.aoscx # <-- Aruba OS


cisco_switches:


aruba_distro:


cisco_routers:
  children:
    S0123:
      hosts:
        S0123RTR001:
          ansible_host: 1.2.3.4
  vars:
    ansible_connection: network_cli # <-- CLI connection method
    ansible_network_os: cisco.ios.ios # <-- used for cisco hosts

  #vars:
    #ansible_connection: network_cli # <-- CLI connection method
    #ansible_network_os: arubanetworks.aoscx.aoscx # <-- Aruba OS


### Template below for inventory - spacing and indentation is crucial ###
### Format is in YAML, all entries are in "key:value" format ###
### Any "key" marked with "**" is an ansible key, and cannot have its name changed ###
### Enter values for all keys needed ###

#S0123:         <-- enter site number or preferred group name
#  hosts**:           <-- enter hosts key and enter all hosts below it
#    host1:               <-- enter name of first host and info of the host below it
#      ansible_host**: 1.2.3.4        <-- IP address of the host
#    host2:
#      ansible_host**: 4.5.6.7


#  vars**:         <--- enter the variables used by all hosts in the site or group number 
#    ansible_connection**: network_cli  <-- used for ios and aoscx network cli
#    ansible_connection**: arubanetworks.aoscx.aoscx  <-- used for REST API modules on aoscx only
#    ansible_network_os**: arubanetworks.aoscx.aoscx  <-- used for aoscx hosts
#    ansible_network_os**: cisco.ios.ios  <-- used for cisco hosts

...