---


- name: SET BOOT DEFAULT TO SECONDARY
  hosts: MAIN
  collections:
    - arubanetworks.aoscx 

  ##  
  vars:
    ansible_tacacs_username: "{{ lookup('file', '/home/ansible/credentials.yml') | from_yaml }}" # used to find the ansible_user tacacs login
    ansible_tacacs_password: "{{ lookup('file', '/home/ansible/credentials.yml') | from_yaml }}" # used to find the ansible_password tacacs login
    ansible_user: "{{ ansible_tacacs_username }}" # reassign to new var
    ansible_password: "{{ ansible_tacacs_password }}" # reassign to new var
    #
    # the firmware update playbook needs to use paramiko ssh type
    #ansible_ssh_type: paramiko

  vars_files: /home/ansible/credentials.yml

  gather_facts: no

  tasks:

    - name: Set Boot Default To Secondary
      vars:
        ansible_command_timeout: 180
      aoscx_command:
        commands:
          - auto-confirm
          - boot set-default secondary
...