---
FIRMWARE_UPDATE:
  hosts:
    SWT001:
      ansible_host: 1.1.1.1
      switch_model: 6300
    SWT002:
      ansible_host: 2.2.2.2
      switch_model: 6300
    SWT002-2:
      ansible_host: 2.2.2.3
      switch_model: 6300
    SWT002-3:
      ansible_host: 2.2.2.4
      switch_model: 6300
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubanetworks.aoscx.aoscx
MAIN:
  hosts:
    SWT001:
      ansible_host: 1.1.1.1
      config_file: /home/user/ansible/ansible_playbooks/refresh/config_files/generated_configs/SWT001_base_config.ios
    SWT003:
      ansible_host: 3.3.3.3
      config_file: /home/user/ansible/ansible_playbooks/refresh/config_files/generated_configs/SWT003_base_config.ios
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubanetworks.aoscx.aoscx
VSF_DEVICES:
  children:
    conductors:
      hosts:
        2.2.2.2:
          link_1: 1/1/151
          link_2: 1/1/52
          member_number: '1'
          member_type: conductor
          secondary_member: '3'
          stack_number: '1'
    members:
      hosts:
        2.2.2.3:
          link_1: 1/1/151
          link_2: 1/1/52
          member_number: '2'
          member_type: member
          secondary_member: ''
          stack_number: '1'
        2.2.2.4:
          link_1: 1/1/151
          link_2: 1/1/52
          member_number: '3'
          member_type: standby
          secondary_member: ''
          stack_number: '1'
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubanetworks.aoscx.aoscx
...
