---
PROV_NET:
  children:
    conductors:
      hosts:
        1.1.1.1:
          link_1: 1/1/27
          link_2: 1/1/28
          member_number: '1'
          member_type: conductor
          secondary_member: '3'
          stack_number: '1'
    members:
      hosts:
        2.2.2.2:
          link_1: 1/1/51
          link_2: 1/1/52
          member_number: '2'
          member_type: member
          secondary_member: ''
          stack_number: '1'
        3.3.3.3:
          link_1: 1/1/51
          link_2: 1/1/52
          member_number: '3'
          member_type: standby
          secondary_member: ''
          stack_number: '1'
  vars:
    ansible_connection: network_cli
    ansible_network_os: arubanetworks.aoscx.aoscx
...
